// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //     apiKey: "Your Api Key",
  //     authDomain: "Your authDomain",
  //     databaseURL: "Paste you databaseURL",
  //     projectId: "Your firebase project id",
  //     storageBucket: "Your firebase storageBucket",
  //     messagingSenderId: "Your firebase messagingSenderId",
  //     appId: "Your firebase appId");

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBgkagPVWtp7736wC_TJRW0EkNrgkt7Jfw",
    authDomain: "pixposbd.firebaseapp.com",
    databaseURL: "https://pixposbd-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "pixposbd",
    storageBucket: "pixposbd.appspot.com",
    messagingSenderId: "906952853387",
    appId: "1:906952853387:web:3f72b8987a2c872608918e",
  );
}
